### ISSUE TITLE
Font style

### ISSUE THREAD

**Issue by vanjavanjavanja** [anshulagarwal06/PasswordEditText#3]
Hi, the font face seems to be different from default Roboto. How can I change it? 
![font](https://cloud.githubusercontent.com/assets/13190732/16614523/6aa2cae6-437a-11e6-927e-e9cbab0aa8fe.PNG)
Thanx!

**Comment by anshulagarwal06** [comment]
Add this line in xml

`android:fontFamily="sans-serif"
`

**Comment by vanjavanjavanja** [comment]
did not help unfortunately
